-- 0001_Documentation_Numbering_Scheme.sql
-- PWMS AC — SQL folder numbering scheme
-- Pure documentation. No executable statements in this file.

-- ==========================================================================
-- RANGES
-- ==========================================================================
-- 0001         Documentation (this file)
-- 1010-1999    Tables — CREATE TABLE only, no DROP needed (IF NOT EXISTS
--              is fully idempotent). Each file is self-contained: columns,
--              constraints, indexes, and GRANTs for that one table.
--              Numbered in dependency order (a table only gets a number
--              once every table it references already has one).
-- 2010-2999    Views — mirror their primary table's number where the
--              view is squarely "that table's detail view"
--              (e.g. 1030 milestone -> 2030 vw_milestone_details).
--              Additional views built on the same table get +1, +2, ...
--              A view spanning multiple tables into a report that isn't
--              flavored by any single one of them gets its own number
--              in the x071+ sub-range instead of being forced into a
--              mirror it doesn't really belong to — e.g. 2071
--              (vw_review_portfolio_time, spans task_log/activity/
--              milestone/project/portfolio) and 2072
--              (vw_payroll_month, spans attendance_log and
--              employment_history equally).
--              DROP VIEW IF EXISTS immediately before CREATE VIEW is
--              normal here — not a corrective patch — since
--              CREATE OR REPLACE VIEW fails outright if the column list
--              changes shape.
-- 3010-3999    Seed data — mirrors table numbering (e.g. 1050 todo ->
--              3050 seed for todo). Only created for tables that
--              actually have seed data; gaps are expected for any
--              table that hasn't yet been through a seed-generation
--              pass (e.g. a new table added later, before its first
--              seed file exists).
-- 4001         RLS — ENABLE ROW LEVEL SECURITY + CREATE POLICY for every
--              table, in one combined file. Deliberately separate from
--              GRANT (which lives inside each table's own file) — GRANT
--              controls whether a role can touch a table at all; RLS
--              controls which rows it sees once it already can. Kept as
--              its own step so a from-scratch rebuild can create schema
--              and load data BEFORE security is switched on, rather than
--              fighting RLS while seeding.
-- 9001-9999    Special / one-time tooling — not part of the repeatable
--              build sequence itself:
--                9001  Schema -> JSON introspection query
--                9002  Live schema snapshot scan (run periodically,
--                      paste output into the sync folder — this is the
--                      verification mechanism that keeps this whole
--                      folder honest against what's actually live)
--                9003  Full master rebuild script — single file,
--                      generated fresh from the individual verified
--                      source files, for standing up a new database
--                      from nothing. Covers every table and view
--                      currently in the folder — regenerate it fresh
--                      whenever a source file changes, rather than
--                      hand-patching it.
--                9004  Cleanup / drop-all script — reverses 9003
--                      exactly, for returning a test/scratch project
--                      to empty. Not part of the build sequence.

-- ==========================================================================
-- WHAT NEVER GOES IN THIS FOLDER
-- ==========================================================================
-- No standalone corrective ALTER/DROP scripts pretending to be part of
-- the repeatable build set. When something needs fixing, the fix is
-- folded directly into that table's own CREATE TABLE statement so the
-- file is simply already correct going forward. History of *why* it
-- changed lives in git commit messages, not in extra numbered files.
