-- 9003_Master_Rebuild.sql
-- Full from-scratch rebuild — every table, view, seed row, and RLS
-- policy in one file, in correct dependency order. Covers all 13
-- tables (the original 8, plus the 5-table Attendance module added
-- later) and all 12 views. Generated by literal concatenation of the
-- individual verified source files, not hand-assembled from memory —
-- regenerate this file fresh whenever those source files change,
-- rather than hand-patching it directly.
--
-- Regenerated this pass specifically to pick up two fixes verified
-- against the live 9002 snapshot: personal_profile.short_name (present,
-- positioned at the end of the column list, matching live's actual
-- physical order) and attendance_log.oracle_updated's default
-- (true, not false).
--
-- Run this top-to-bottom on a genuinely empty database to stand up a
-- complete copy of PWMS AC's schema, Attendance module included. Load
-- your data export separately afterward (this file has real seed data
-- for every table, since all 13 now have a seed file — but it's not a
-- substitute for your actual live data if you're restoring, not
-- starting fresh).
--
-- 9010_Attendance_Master_Rebuild.sql is retired now that this file
-- covers everything — safe to delete.

-- ==========================================================================
-- SOURCE: 1010_Create_Portfolio.sql
-- ==========================================================================
-- 1010_Create_Portfolio.sql

create table if not exists portfolio (

    portfolio_id uuid
        primary key
        default gen_random_uuid(),

    portfolio_name text
        not null,

    portfolio_type text
        not null,

    description text,

    enabled boolean
        not null
        default true,

    display_order integer
        default 100,

    created_at timestamptz
        not null
        default now(),

    created_by text
        not null
        default 'System',

    updated_at timestamptz
        not null
        default now(),

    updated_by text
        not null
        default 'System'
);

create unique index if not exists
uq_portfolio_name
on portfolio(portfolio_name);

create index if not exists
idx_portfolio_name
on portfolio(portfolio_name);

create index if not exists
idx_portfolio_enabled
on portfolio(enabled);

grant all on table portfolio to anon;
grant all on table portfolio to authenticated;


-- ==========================================================================
-- SOURCE: 1020_Create_Project.sql
-- ==========================================================================
-- 1020_Create_Project.sql

create table if not exists project (

    project_id uuid
        primary key
        default gen_random_uuid(),

    portfolio_id uuid
        not null
        references portfolio(portfolio_id),

    project_code text
        not null,

    project_name text
        not null,

    description text,

    display_order integer
        not null
        default 100,

    -- KNOWN BROKEN DEFAULT — reproduced exactly as it exists live, not
    -- fixed. Confirmed dormant: every project row today has a clean
    -- status value, meaning every insert always sets status explicitly
    -- and this default has never actually fired. Left unfixed
    -- intentionally per instruction; revisit as its own conversation
    -- later rather than silently correcting it here.
    status text
        default '''Not Started''::text'::text,

    enabled boolean
        not null
        default true,

    start_date date,

    target_date date,

    created_at timestamptz
        not null
        default now(),

    created_by text
        not null
        default 'System',

    updated_at timestamptz
        not null
        default now(),

    updated_by text
        not null
        default 'System'
);

create unique index if not exists
uq_project_code
on project(project_code);

create unique index if not exists
uq_project_name_per_portfolio
on project(portfolio_id, project_name);

create index if not exists
idx_project_portfolio
on project(portfolio_id);

create index if not exists
idx_project_enabled
on project(enabled);

grant all on table project to anon;
grant all on table project to authenticated;


-- ==========================================================================
-- SOURCE: 1030_Create_Milestone.sql
-- ==========================================================================
-- 1030_Create_Milestone.sql

create table if not exists milestone (

    milestone_id uuid
        primary key
        default gen_random_uuid(),

    project_id uuid
        not null
        references project(project_id),

    milestone_code text
        not null,

    milestone_name text
        not null,

    description text,

    start_date date,

    target_date date,

    status text
        not null
        default 'Not Started',

    display_order integer
        not null
        default 100,

    enabled boolean
        not null
        default true,

    created_at timestamptz
        not null
        default now(),

    created_by text
        not null
        default 'System',

    updated_at timestamptz
        not null
        default now(),

    updated_by text
        not null
        default 'System'
);

create unique index if not exists
uq_milestone_code
on milestone(milestone_code);

create unique index if not exists
uq_milestone_name_per_project
on milestone(project_id, milestone_name);

create index if not exists
idx_milestone_project
on milestone(project_id);

create index if not exists
idx_milestone_enabled
on milestone(enabled);

create index if not exists
idx_milestone_status
on milestone(status);

grant all on table milestone to anon;
grant all on table milestone to authenticated;


-- ==========================================================================
-- SOURCE: 1040_Create_Activity.sql
-- ==========================================================================
-- 1040_Create_Activity.sql
-- Legacy entity, retained in the database, removed from UI navigation.

create table if not exists activity (

    activity_id uuid
        primary key
        default gen_random_uuid(),

    milestone_id uuid
        references milestone(milestone_id),

    activity_name text
        not null,

    description text,

    target_date date,

    priority text
        default 'Medium',

    status text
        default 'Open',

    display_order integer
        default 100,

    enabled boolean
        default true,

    created_at timestamptz
        default now(),

    created_by text
        default 'System',

    updated_at timestamptz
        default now(),

    updated_by text
        default 'System'
);

create index if not exists
idx_activity_milestone
on activity(milestone_id);

grant all on table activity to anon;
grant all on table activity to authenticated;


-- ==========================================================================
-- SOURCE: 1050_Create_Todo.sql
-- ==========================================================================
-- 1050_Create_Todo.sql

create table if not exists todo (

    todo_id uuid primary key
        default gen_random_uuid(),

    -- Legacy hook, retained but NOT NULL. Note: no FK constraint to
    -- activity — that constraint was dropped live at some point and
    -- this file now matches that reality, rather than the old file's
    -- "references activity(activity_id)" which no longer reflects what
    -- actually exists in the database.
    activity_id uuid not null,

    todo_text text not null,

    notes text,

    status text not null
        default 'Open',

    due_date date,

    display_order integer
        default 100,

    enabled boolean
        default true,

    created_at timestamptz
        default now(),

    created_by text,

    updated_at timestamptz
        default now(),

    updated_by text,

    -- The real milestone linkage this app actually runs on. Missing
    -- from every prior version of this file despite being live and
    -- load-bearing since early in the project — added here from the
    -- verified 9002 snapshot, not from memory.
    milestone_id uuid
        references milestone(milestone_id)
);

grant all on table todo to anon;
grant all on table todo to authenticated;


-- ==========================================================================
-- SOURCE: 1060_Create_TaskLog.sql
-- ==========================================================================
-- 1060_Create_TaskLog.sql

create table if not exists task_log (

    task_log_id uuid
        primary key
        default gen_random_uuid(),

    -- Legacy hook, nullable, no FK constraint (dropped live to allow
    -- ToDo-only logging once task_log.todo_id became the primary path).
    activity_id uuid,

    task_date date
        not null
        default current_date,

    task_description text
        not null,

    minutes_spent integer
        not null
        default 0,

    start_time time,

    end_time time,

    display_order integer
        not null
        default 100,

    created_at timestamptz
        not null
        default now(),

    created_by text
        not null
        default 'System',

    updated_at timestamptz
        not null
        default now(),

    updated_by text
        not null
        default 'System',

    -- The real ToDo linkage this app actually runs on. Missing from
    -- every prior version of this file despite being live and
    -- load-bearing since early in the project — added here from the
    -- verified 9002 snapshot, not from memory.
    todo_id uuid
        references todo(todo_id)
);

create index if not exists
idx_task_log_activity
on task_log(activity_id);

create index if not exists
idx_task_log_date
on task_log(task_date);

grant all on table task_log to anon;
grant all on table task_log to authenticated;


-- ==========================================================================
-- SOURCE: 1070_Create_UpdatePrepSettings.sql
-- ==========================================================================
-- 1070_Create_UpdatePrepSettings.sql
-- Generic key/value store for the Update Prep page — style instructions,
-- templates, attachment mode, recency, all per format, plus shared
-- spoken style. One row per setting_key.

create table if not exists update_prep_settings (
    setting_key text primary key,
    setting_value text,
    updated_at timestamptz not null default now()
);

grant all on table update_prep_settings to anon;
grant all on table update_prep_settings to authenticated;


-- ==========================================================================
-- SOURCE: 1080_Create_UpdatePrepHistory.sql
-- ==========================================================================
-- 1080_Create_UpdatePrepHistory.sql
-- Append-only log, one row per period per format. Written and spoken
-- content share the same row for a given format+period, updated in
-- place as each half gets saved.

create table if not exists update_prep_history (
    history_id uuid primary key default gen_random_uuid(),
    format text not null,                  -- 'manager' or 'csaio'
    period_from date not null,
    period_to date not null,
    generated_prompt text,
    finished_update text,
    spoken_prompt text,
    finished_spoken text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists
idx_update_prep_history_format_date
on update_prep_history (format, period_to desc);

grant all on table update_prep_history to anon;
grant all on table update_prep_history to authenticated;


-- ==========================================================================
-- SOURCE: 1090_Create_PersonalProfile.sql
-- ==========================================================================
-- 1090_Create_PersonalProfile.sql
-- Permanent, employer-independent personal facts. Single row, updated
-- in place — this is who you are, not where you currently work.
--
-- Regenerated from the verified live 9002 snapshot, not patched —
-- column order matches live exactly (short_name sits at the end,
-- since it was added later via ALTER TABLE, which always appends).

create table if not exists personal_profile (

    profile_id uuid
        primary key
        default gen_random_uuid(),

    first_name text,
    middle_name text,
    last_name text,
    full_name text,
    short_name text,

    dob date,
    gender text,

    personal_email text,
    qualification text,

    mobile_primary text,
    mobile_secondary text,

    res_address_1 text,
    res_address_2 text,
    res_pin text,
    res_city text,
    res_state text,

    total_experience_years numeric,

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now()
);

grant all on table personal_profile to anon;
grant all on table personal_profile to authenticated;


-- ==========================================================================
-- SOURCE: 1100_Create_EmploymentHistory.sql
-- ==========================================================================
-- 1100_Create_EmploymentHistory.sql
-- One row per employment stint. A future job change closes the current
-- row (sets end_date) and opens a new one — old rows are never
-- overwritten, giving genuine history rather than a single flat
-- profile that loses everything the moment you update it.
--
-- payroll_cycle_start_day / end_day are scoped to THIS employment stint
-- specifically (e.g. 25 / 24), since a future employer could run a
-- completely different cycle — this is not a single global rule.

create table if not exists employment_history (

    employment_id uuid
        primary key
        default gen_random_uuid(),

    employer_name text,
    manager_name text,
    designation text,
    department text,

    band text,
    region text,
    location text,
    site text,
    city text,

    work_email text,
    employee_no text,
    sap_id text,
    windows_login_id text,
    windows_domain text,

    bu text,

    delivery_head text,
    delivery_team text,
    resource_cat text,
    msoffice_cat text,

    asset_details text,
    asset_issue_date date,

    mem_activated boolean,
    record_created_datetime timestamptz,
    active_status integer,
    last_working_day date,

    payroll_cycle_start_day integer,
    payroll_cycle_end_day integer,

    start_date date
        not null,

    end_date date,
    -- null = current employment

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now()
);

create index if not exists
idx_employment_history_dates
on employment_history(start_date, end_date);

grant all on table employment_history to anon;
grant all on table employment_history to authenticated;


-- ==========================================================================
-- SOURCE: 1110_Create_AttendanceCodes.sql
-- ==========================================================================
-- 1110_Create_AttendanceCodes.sql
-- The current, evolving master list of codes. Free to grow when you
-- change employers — new codes get added, old ones are never deleted,
-- since historical attendance_log rows freeze their own description
-- and hr_type at the moment they're logged and never re-read this
-- table afterward.

create table if not exists attendance_codes (

    code text
        primary key,

    attendance_type text
        not null,
    -- e.g. "Present", "Privilege Leave", "UnPaid Leave"

    remarks text,

    hr_type text
        not null,
    -- one of: Presence, Leave, WeekOff, Holiday

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now()
);

grant all on table attendance_codes to anon;
grant all on table attendance_codes to authenticated;


-- ==========================================================================
-- SOURCE: 1120_Create_HolidayMaster.sql
-- ==========================================================================
-- 1120_Create_HolidayMaster.sql

create table if not exists holiday_master (

    holiday_id uuid
        primary key
        default gen_random_uuid(),

    holiday_date date
        not null,

    holiday_name text
        not null,

    holiday_type text
        not null,
    -- Fixed or Floating

    locations text,
    -- e.g. "All India", "MAH" — kept as informational metadata

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now()
);

create unique index if not exists
uq_holiday_master_date
on holiday_master(holiday_date);

grant all on table holiday_master to anon;
grant all on table holiday_master to authenticated;


-- ==========================================================================
-- SOURCE: 1130_Create_AttendanceLog.sql
-- ==========================================================================
-- 1130_Create_AttendanceLog.sql
-- One row per day, log_date itself as the primary key — duplicate
-- entries for the same day are impossible by construction, not by
-- application-level checking.
--
-- Regenerated from the verified live 9002 snapshot, not patched.
--
-- Three text fields serve three different, deliberately separate jobs:
--   reason           — yours, freely editable any time
--   description      — frozen copy of attendance_codes.attendance_type
--                       at the moment this was logged, never re-read
--                       or recalculated afterward
--   hr_type_frozen   — frozen copy of attendance_codes.hr_type,
--                       same reasoning
-- Both frozen fields exist so a future redefinition of what a code
-- means can never silently rewrite what an old entry meant when it
-- was actually logged.

create table if not exists attendance_log (

    log_date date
        primary key,

    code text
        not null
        references attendance_codes(code),

    reason text,

    description text,
    -- frozen at insert, not a live join

    hr_type_frozen text,
    -- frozen at insert, not a live join

    oracle_updated boolean
        default true,
    -- renamed from the old SAMAY flag — same purpose, tracks the
    -- current HRIS system (Oracle), not SAMAY specifically. Defaults
    -- true since it rarely fires in practice — the app always sends
    -- an explicit value (checkbox state, or hardcoded true for bulk
    -- weekend fill); this default only matters as a fallback for
    -- anything inserted outside the app's own code paths.

    created_at timestamptz
        not null
        default now(),

    updated_at timestamptz
        not null
        default now()
);

create index if not exists
idx_attendance_log_code
on attendance_log(code);

grant all on table attendance_log to anon;
grant all on table attendance_log to authenticated;


-- ==========================================================================
-- SOURCE: 2030_View_MilestoneDetails.sql
-- ==========================================================================
-- 2030_View_MilestoneDetails.sql

drop view if exists vw_milestone_details;

create view vw_milestone_details as

select

    m.milestone_id,
    m.project_id,
    p.portfolio_id,

    m.milestone_code,
    m.milestone_name,

    p.project_code,
    p.project_name,

    pf.portfolio_name,
    pf.portfolio_type,

    m.description,

    m.start_date,
    m.target_date,

    m.status,
    m.enabled,

    m.created_at,
    m.created_by,

    m.updated_at,
    m.updated_by

from milestone m

inner join project p
    on p.project_id = m.project_id

inner join portfolio pf
    on pf.portfolio_id = p.portfolio_id;

grant select on vw_milestone_details to anon;
grant select on vw_milestone_details to authenticated;


-- ==========================================================================
-- SOURCE: 2040_View_ActivityDetails.sql
-- ==========================================================================
-- 2040_View_ActivityDetails.sql

drop view if exists vw_activity_details;

create view vw_activity_details as

select

    a.activity_id,
    a.activity_name,
    a.description,
    a.target_date,
    a.priority,
    a.status,
    a.display_order,
    a.enabled,

    a.created_at,
    a.created_by,

    a.updated_at,
    a.updated_by,

    a.milestone_id,

    m.milestone_name,

    m.project_id,
    m.project_name,

    m.portfolio_id,
    m.portfolio_name

from activity a

left join vw_milestone_details m
    on m.milestone_id = a.milestone_id;

grant select on vw_activity_details to anon;
grant select on vw_activity_details to authenticated;


-- ==========================================================================
-- SOURCE: 2041_View_ReviewOpenActivities.sql
-- ==========================================================================
-- 2041_View_ReviewOpenActivities.sql

drop view if exists vw_review_open_activities;

create view vw_review_open_activities as

select

    activity_id,
    activity_name,
    status,
    target_date,
    portfolio_name,
    project_name,
    milestone_name,
    enabled

from vw_activity_details

where
    enabled = true
    and status not in ('Completed', 'Cancelled');

grant select on vw_review_open_activities to anon;
grant select on vw_review_open_activities to authenticated;


-- ==========================================================================
-- SOURCE: 2042_View_ReviewActivitySummary.sql
-- ==========================================================================
-- 2042_View_ReviewActivitySummary.sql

drop view if exists vw_review_activity_summary;

create view vw_review_activity_summary as

select

    count(*) filter (
        where enabled = true
        and status not in ('Completed', 'Cancelled')
    ) as open_activities,

    count(*) filter (
        where enabled = true
        and status = 'In Progress'
    ) as in_progress_activities,

    count(*) filter (
        where enabled = true
        and status = 'Completed'
        and updated_at >= date_trunc('week', current_date)
    ) as completed_activities,

    count(*) filter (
        where enabled = true
        and status not in ('Completed', 'Cancelled')
        and target_date < current_date
    ) as overdue_activities

from activity;

grant select on vw_review_activity_summary to anon;
grant select on vw_review_activity_summary to authenticated;


-- ==========================================================================
-- SOURCE: 2050_View_Todo.sql
-- ==========================================================================
-- 2050_View_Todo.sql

drop view if exists vw_todo;

create view vw_todo as

select

    t.todo_id,
    t.todo_text,
    t.notes,
    t.status,
    t.due_date,
    t.display_order,
    t.enabled,

    t.created_at,
    t.created_by,

    t.updated_at,
    t.updated_by,

    t.milestone_id,

    m.milestone_name,

    p.project_id,
    p.project_name,

    pf.portfolio_id,
    pf.portfolio_name

from todo t

left join milestone m
    on t.milestone_id = m.milestone_id

left join project p
    on m.project_id = p.project_id

left join portfolio pf
    on p.portfolio_id = pf.portfolio_id

where t.enabled = true;

grant all on table vw_todo to anon;
grant all on table vw_todo to authenticated;


-- ==========================================================================
-- SOURCE: 2060_View_TaskLogDetails.sql
-- ==========================================================================
-- 2060_View_TaskLogDetails.sql

drop view if exists vw_task_log_details;

create view vw_task_log_details as

select

    tl.task_log_id,
    tl.task_date,
    tl.task_description,
    tl.minutes_spent,
    tl.start_time,
    tl.end_time,
    tl.display_order,

    tl.created_at,
    tl.created_by,

    tl.updated_at,
    tl.updated_by,

    tl.todo_id,
    t.todo_text,

    tl.activity_id,
    a.activity_name,

    m.milestone_id,
    m.milestone_name,

    p.project_id,
    p.project_name

from task_log tl

left join todo t
    on tl.todo_id = t.todo_id

left join activity a
    on tl.activity_id = a.activity_id

left join milestone m
    on coalesce(t.milestone_id, a.milestone_id) = m.milestone_id

left join project p
    on m.project_id = p.project_id;

grant select on vw_task_log_details to anon;
grant select on vw_task_log_details to authenticated;


-- ==========================================================================
-- SOURCE: 2061_View_ReviewRecentLogs.sql
-- ==========================================================================
-- 2061_View_ReviewRecentLogs.sql

drop view if exists vw_review_recent_logs;

create view vw_review_recent_logs as

select *
from vw_task_log_details
order by task_date desc, start_time desc;

grant select on vw_review_recent_logs to anon;
grant select on vw_review_recent_logs to authenticated;


-- ==========================================================================
-- SOURCE: 2062_View_ReviewTimeSummary.sql
-- ==========================================================================
-- 2062_View_ReviewTimeSummary.sql

drop view if exists vw_review_time_summary;

create view vw_review_time_summary as

select

    coalesce(
        sum(
            case
                when task_date = current_date
                then minutes_spent
                else 0
            end
        ),
        0
    ) as today_minutes,

    coalesce(
        sum(
            case
                when task_date >= date_trunc('week', current_date)::date
                then minutes_spent
                else 0
            end
        ),
        0
    ) as week_minutes,

    coalesce(
        sum(
            case
                when task_date >= date_trunc('month', current_date)::date
                then minutes_spent
                else 0
            end
        ),
        0
    ) as month_minutes

from task_log;

grant select on vw_review_time_summary to anon;
grant select on vw_review_time_summary to authenticated;


-- ==========================================================================
-- SOURCE: 2071_View_ReviewPortfolioTime.sql
-- ==========================================================================
-- 2071_View_ReviewPortfolioTime.sql
-- NOTE: this view only joins task_log -> activity -> milestone. It has
-- no awareness of the newer task_log.todo_id path, so hours logged
-- against a ToDo (most current logging) are miscounted into
-- "Standalone Activities." Left exactly as-is per instruction, matching
-- live behavior precisely rather than silently correcting it here.

drop view if exists vw_review_portfolio_time;

create view vw_review_portfolio_time as

select

    coalesce(p.portfolio_name, 'Standalone Activities') as portfolio_name,

    round(sum(t.minutes_spent) / 60.0, 1) as hours_spent

from task_log t

left join activity a
    on t.activity_id = a.activity_id

left join milestone m
    on a.milestone_id = m.milestone_id

left join project pr
    on m.project_id = pr.project_id

left join portfolio p
    on pr.portfolio_id = p.portfolio_id

group by portfolio_name

order by hours_spent desc;

grant select on vw_review_portfolio_time to anon;
grant select on vw_review_portfolio_time to authenticated;


-- ==========================================================================
-- SOURCE: 2072_View_PayrollMonth.sql
-- ==========================================================================
-- 2072_View_PayrollMonth.sql
-- Cross-table report, not flavored by a single table — matches an
-- attendance_log row to whichever employment_history stint was active
-- on that date, then computes the payroll month/year using THAT
-- stint's own cycle days (not a single global rule), since a future
-- employer could run a different cycle entirely.
--
-- Rarely used — mainly relevant around a Last Working Day. Left as its
-- own separate view rather than folded into the everyday attendance
-- pages, per instruction.

drop view if exists vw_payroll_month;

create view vw_payroll_month as

select

    al.log_date,
    al.code,
    al.description,
    al.hr_type_frozen,

    eh.employer_name,
    eh.payroll_cycle_start_day,
    eh.payroll_cycle_end_day,

    case
        when extract(day from al.log_date) >= eh.payroll_cycle_start_day
        then case
                when extract(month from al.log_date) = 12 then 1
                else extract(month from al.log_date) + 1
             end
        else extract(month from al.log_date)
    end as payroll_month,

    case
        when extract(day from al.log_date) >= eh.payroll_cycle_start_day
             and extract(month from al.log_date) = 12
        then extract(year from al.log_date) + 1
        else extract(year from al.log_date)
    end as payroll_year

from attendance_log al

left join employment_history eh
    on al.log_date >= eh.start_date
    and (eh.end_date is null or al.log_date <= eh.end_date);

grant select on vw_payroll_month to anon;
grant select on vw_payroll_month to authenticated;


-- ==========================================================================
-- SOURCE: 2100_View_CurrentEmployment.sql
-- ==========================================================================
-- 2100_View_CurrentEmployment.sql
-- Convenience view — "give me my current job" without every page
-- needing to repeat the end_date IS NULL filter itself.

drop view if exists vw_current_employment;

create view vw_current_employment as

select *
from employment_history
where end_date is null
order by start_date desc
limit 1;

grant select on vw_current_employment to anon;
grant select on vw_current_employment to authenticated;


-- ==========================================================================
-- SOURCE: 2130_View_AttendanceLog.sql
-- ==========================================================================
-- 2130_View_AttendanceLog.sql
-- Plain ordered passthrough — kept consistent with the rest of the app's
-- convention of always reading through a view, even for a 1:1 relationship.

drop view if exists vw_attendance_log;

create view vw_attendance_log as

select *
from attendance_log
order by log_date desc;

grant select on vw_attendance_log to anon;
grant select on vw_attendance_log to authenticated;


-- ==========================================================================
-- SOURCE: 3050_Seed_Todo.sql
-- ==========================================================================
-- 3050_Seed_Todo.sql
-- Only seed script that currently exists. The rest are a deliberate,
-- deferred one-time activity: once data export is complete, all seed
-- scripts get regenerated from real exported data instead.

insert into todo (

    activity_id,
    todo_text,
    due_date,
    created_by,
    updated_by

)

select

    activity_id,
    'Test ToDo',
    current_date,
    'system',
    'system'

from activity

limit 1;


-- ==========================================================================
-- SOURCE: 3090_Seed_PersonalProfile.sql
-- ==========================================================================
-- 3090_Seed_PersonalProfile.sql
-- Real values from the original Excel EMPMaster sheet.

insert into personal_profile (
    short_name, first_name, middle_name, last_name, full_name,
    dob, gender,
    personal_email, qualification,
    mobile_primary, mobile_secondary,
    res_address_1, res_address_2, res_pin, res_city, res_state,
    total_experience_years
) values (
    'Abhishek N', 'Abhishek', 'Ratan', 'Nandrajog', 'Abhishek Ratan Nandrajog',
    '1980-09-18', 'Male',
    'abhishek.nandrajog@gmail.com', 'Master of Science (Computer Science)',
    '9820021120', '9029004771',
    'E/204, Trishul Ganga,', 'Sindhi Society, Chembur.', '400071', 'Mumbai', 'Maharashtra',
    19
);


-- ==========================================================================
-- SOURCE: 3100_Seed_EmploymentHistory.sql
-- ==========================================================================
-- 3100_Seed_EmploymentHistory.sql
-- One open row (end_date NULL), exact EMPMaster values as they stood in
-- the original Excel. You've flagged several of these as stale
-- (Manager, work email, etc.) — this seeds them exactly as-is per your
-- instruction, for you to correct in place later rather than guessing
-- at current values here.

insert into employment_history (
    employer_name, manager_name, designation, department,
    band, region, location, site, city,
    work_email, employee_no, sap_id, windows_login_id, windows_domain,
    bu,
    delivery_head, delivery_team, resource_cat, msoffice_cat,
    asset_details, asset_issue_date,
    mem_activated, record_created_datetime, active_status, last_working_day,
    payroll_cycle_start_day, payroll_cycle_end_day,
    start_date, end_date
) values (
    null, 'Aakash Shripat', 'Associate Vice President', 'Digital Solutions',
    'Band 2 (AVP Level)', 'Mumbai', 'Kurla', 'Mumbai Corporate', 'Mumbai',
    'abhishek.nandrajog@teleperformancedibs.com', '80507527', '80507527', 'abhishek.nandrajog', 'aegisglobal.com',
    'IBU',
    'Abhinandan Jain', null, 'Shared', 'E3',
    'Laptop: SR. NO.:  || ASSET TAG:  || DELL LATITUDE 3420', '2022-05-30',
    true, '2022-05-30 00:00:00+00', 1, null,
    25, 24,
    '2022-05-30', null
);


-- ==========================================================================
-- SOURCE: 3110_Seed_AttendanceCodes.sql
-- ==========================================================================
-- 3110_Seed_AttendanceCodes.sql
-- Exact 10-row master from the original AttendanceCodes sheet.

insert into attendance_codes (code, attendance_type, remarks, hr_type) values
('P', 'Present', 'Present', 'Presence'),
('WFH', 'Work From Home', 'Work From Home', 'Presence'),
('LWD-RES', 'Present', 'Last Working Day - Resigned', 'Presence'),
('OFF', 'Week-Off', 'Weekly-Off', 'WeekOff'),
('H', 'Holiday', 'Fixed Holiday', 'Holiday'),
('FH', 'Holiday', 'Floating Holiday', 'Holiday'),
('PL', 'Privilege Leave', 'Privileged Leave', 'Leave'),
('CL', 'Casual Leave', 'Casual Leave', 'Leave'),
('LP', 'UnPaid Leave', 'Loss Of Pay', 'Leave'),
('SUPL', 'Special UnPaid Leave', 'Special UnPaid Leave', 'Leave');


-- ==========================================================================
-- SOURCE: 3120_Seed_HolidayMaster.sql
-- ==========================================================================
-- 3120_Seed_HolidayMaster.sql
-- Exact 41-row master from the original HolidayMaster sheet, 2022–2026.
-- The old sheet's "Future Holidays?" completed/future flag is not
-- carried forward as a stored column — it's trivially derivable by
-- comparing holiday_date to today, and storing it would just go stale.

insert into holiday_master (holiday_date, holiday_name, holiday_type, locations) values
('2022-01-01', 'New Year', 'Fixed', 'All India'),
('2022-01-26', 'Republic Day', 'Fixed', 'All India'),
('2022-08-15', 'Independence Day', 'Fixed', 'All India'),
('2022-10-02', 'Mahatama Gandhi Jayanti', 'Fixed', 'All India'),
('2022-03-01', 'Mahashivratri', 'Floating', 'MAH'),
('2022-03-18', 'Holi', 'Floating', 'MAH'),
('2022-08-31', 'Ganesh Chaturthi', 'Floating', 'MAH'),
('2022-10-05', 'Dussera', 'Floating', 'MAH'),
('2022-10-24', 'Diwali', 'Floating', 'MAH'),
('2022-10-26', 'Bhai Dooj', 'Floating', 'MAH'),

('2023-01-01', 'Happy New Year', 'Floating', 'All India'),
('2023-01-26', 'Republic Day', 'Fixed', 'MAH'),
('2023-03-08', 'Holi', 'Floating', 'MAH'),
('2023-03-22', 'Gudi Padva', 'Floating', 'MAH'),
('2023-05-01', 'Maharashtrian New Year', 'Floating', 'MAH'),
('2023-08-15', 'Independence Day', 'Fixed', 'MAH'),
('2023-09-19', 'Ganesh Chaturthi', 'Floating', 'MAH'),
('2023-10-02', 'Mahatma Gandhi Jayanti', 'Fixed', 'MAH'),
('2023-11-13', 'Diwali', 'Floating', 'MAH'),
('2023-12-25', 'Christmas', 'Floating', 'MAH'),

('2024-01-01', 'New Year', 'Fixed', 'MAH'),
('2024-01-26', 'Republic Day', 'Fixed', 'MAH'),
('2024-03-25', 'Holi', 'Fixed', 'MAH'),
('2024-05-01', 'Maharashtra Din', 'Fixed', 'MAH'),
('2024-08-15', 'Independence Day', 'Fixed', 'MAH'),
('2024-10-02', 'Mahatma Gandhi Jayanti', 'Fixed', 'MAH'),
('2024-11-01', 'Diwali', 'Fixed', 'MAH'),
('2024-12-25', 'Christmas', 'Fixed', 'MAH'),

('2025-01-01', 'New Year', 'Fixed', 'All India'),
('2025-03-14', 'Holi', 'Fixed', 'MAH'),
('2025-05-01', 'Maharashtra Din', 'Fixed', 'MAH'),
('2025-08-15', 'Independence Day', 'Fixed', 'All India'),
('2025-08-27', 'Ganesh Chaturthi', 'Fixed', 'MAH'),
('2025-10-02', 'Mahatma Gandhi Jayanti', 'Fixed', 'All India'),
('2025-10-21', 'Diwali', 'Fixed', 'MAH'),
('2025-12-25', 'Christmas Day', 'Fixed', 'All India'),

('2026-01-01', 'New Year', 'Fixed', 'All India'),
('2026-01-26', 'Republic Day', 'Fixed', 'All India'),
('2026-03-03', 'Holi', 'Fixed', 'All India'),
('2026-05-01', 'Maharashtra Din', 'Fixed', 'MAH'),
('2026-09-14', 'Ganesh Chaturthi', 'Fixed', 'MAH'),
('2026-10-02', 'Mahatma Gandhi Jayanti', 'Fixed', 'All India'),
('2026-11-10', 'Diwali', 'Fixed', 'All India'),
('2026-12-25', 'Christmas', 'Fixed', 'All India');


-- ==========================================================================
-- SOURCE: 3130_Seed_AttendanceLog.sql
-- ==========================================================================
-- 3130_Seed_AttendanceLog.sql
-- Deliberately empty for now.
--
-- 1,501 real historical entries exist in the original Excel (30 May
-- 2022 through 10 Jul 2026), but bulk-importing all of them belongs to
-- its own separate, later decision — once the Attendance UI actually
-- exists to review data quality first (the ".." trailing-dot artifact
-- on weekend reasons, the non-chronological row order, the placeholder
-- "Update Time" values on the earliest entries, etc.) — not something
-- to import blindly as part of this initial schema pass.


-- ==========================================================================
-- SOURCE: 4001_RLS_AllTables.sql
-- ==========================================================================
-- 4001_RLS_AllTables.sql
-- Single combined RLS step for every table — deliberately separate from
-- schema/data so a from-scratch rebuild can create tables and load seed
-- data before security is switched on, rather than fighting RLS while
-- seeding.
--
-- DROP POLICY IF EXISTS before each CREATE POLICY — Postgres has no
-- CREATE POLICY IF NOT EXISTS, so without this guard, re-running this
-- file a second time (e.g. after a partial rebuild) would error out on
-- "policy already exists" and halt partway through.

-- ==========================================================================
-- STEP 1: Policies (permissive single-user pattern, same for every table)
-- ==========================================================================

drop policy if exists "Universal manage on portfolio" on portfolio;
create policy "Universal manage on portfolio" on portfolio
    for all to public using (true) with check (true);

drop policy if exists "Universal manage on project" on project;
create policy "Universal manage on project" on project
    for all to public using (true) with check (true);

drop policy if exists "Universal manage on milestone" on milestone;
create policy "Universal manage on milestone" on milestone
    for all to public using (true) with check (true);

drop policy if exists "Universal manage on activity" on activity;
create policy "Universal manage on activity" on activity
    for all to public using (true) with check (true);

drop policy if exists "Universal manage on todo" on todo;
create policy "Universal manage on todo" on todo
    for all to public using (true) with check (true);

drop policy if exists "Universal manage on task_log" on task_log;
create policy "Universal manage on task_log" on task_log
    for all to public using (true) with check (true);

drop policy if exists "Universal manage on update_prep_settings" on update_prep_settings;
create policy "Universal manage on update_prep_settings" on update_prep_settings
    for all to public using (true) with check (true);

drop policy if exists "Universal manage on update_prep_history" on update_prep_history;
create policy "Universal manage on update_prep_history" on update_prep_history
    for all to public using (true) with check (true);

-- ==========================================================================
-- STEP 2: Enable RLS (the security wall itself)
-- ==========================================================================

alter table portfolio enable row level security;
alter table project enable row level security;
alter table milestone enable row level security;
alter table activity enable row level security;
alter table todo enable row level security;
alter table task_log enable row level security;
alter table update_prep_settings enable row level security;
alter table update_prep_history enable row level security;


-- ==========================================================================
-- ATTENDANCE MODULE
-- ==========================================================================

-- Same pattern as above — permissive policy first, then RLS enabled,
-- for each of the 5 attendance tables.

-- ==========================================================================
-- Add to STEP 1 (Policies)
-- ==========================================================================

drop policy if exists "Universal manage on personal_profile" on personal_profile;
create policy "Universal manage on personal_profile" on personal_profile
    for all to public using (true) with check (true);

drop policy if exists "Universal manage on employment_history" on employment_history;
create policy "Universal manage on employment_history" on employment_history
    for all to public using (true) with check (true);

drop policy if exists "Universal manage on attendance_codes" on attendance_codes;
create policy "Universal manage on attendance_codes" on attendance_codes
    for all to public using (true) with check (true);

drop policy if exists "Universal manage on holiday_master" on holiday_master;
create policy "Universal manage on holiday_master" on holiday_master
    for all to public using (true) with check (true);

drop policy if exists "Universal manage on attendance_log" on attendance_log;
create policy "Universal manage on attendance_log" on attendance_log
    for all to public using (true) with check (true);

-- ==========================================================================
-- STEP 2 (Enable RLS), continued
-- ==========================================================================

alter table personal_profile enable row level security;
alter table employment_history enable row level security;
alter table attendance_codes enable row level security;
alter table holiday_master enable row level security;
alter table attendance_log enable row level security;




